# Generated by Django 3.0.4 on 2020-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.TextField()),
                ('titre', models.TextField()),
                ('date_pub', models.DateTimeField()),
            ],
        ),
    ]
