# Generated by Django 3.0.4 on 2020-03-11 14:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
