# Generated by Django 3.0.4 on 2020-03-12 10:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('adresse', models.TextField()),
                ('cp', models.TextField()),
                ('tel', models.TextField()),
                ('date_naissance', models.DateTimeField()),
                ('date_entre', models.DateTimeField()),
                ('date_sortie', models.DateTimeField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
