# Generated by Django 3.0.4 on 2020-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_membre_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='cp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_entre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_naissance',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_sortie',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='prenom',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='tel',
            field=models.TextField(null=True),
        ),
    ]
