# Generated by Django 3.0.4 on 2020-03-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_membre_promotion'),
        ('typeMembre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemembre',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Membre'),
        ),
    ]
